### ISSUE TITLE
Change VM branch on the fly

### ISSUE THREAD

**Issue by romuleald** [ricofehr/nextdeploy-webui#4]
Being able to change the current branch of you own VM would be useful, that would let us to check something quickly

**Comment by ricofehr** [comment]
I dont agree with that. Because a branch change is a big change: sometimes project are completely different between branchs, sometimes it's not possible because local changes, ...
So i mean, there is no way to implement this features without dirty compromises. If you want test project in other branch, you launch a new vm. It's not very long (~10min) and it's clean and tested method.
And anyway, if you really want change branch on your vm, you can already do it ... manually ! You can connect into vm by ssh, or directly by vnc on the webui (term popin), execute git command and some other build needs, ...
So, i dont recommand this (i prefer launch new vm), but you can doing it if you want.

**Comment by romuleald** [comment]
It could be a setting of the project (or the VM) that give the ability to do this, that VM would be visible only by the VM's creator.
The local change could be erased by `git checkout -f`

**Comment by ricofehr** [comment]
hehe je sais bien Antoine, on peut cleaner les changements locals. Je dis juste que pour faire cela bien, c'est compliqué à mettre en place pour prendre en compte tout les différents cas. Et que du coup, le rapport entre "mettre en place une grosse usine à gaz" sur le sujet et le garder les choses comme maintenant (c à d pas de workflow automatisé mais lancement d'une vm ou changement de branche à la manno) me paraît clairement aller vers le second choix.
Bref, j'ai réfléchi à cette problématique depuis longtemps et j'en suis arrivé pour l'instant à la conclusion "dont change anything if it works".

**Comment by ricofehr** [comment]
Pour finir, merci pour ta remontée !
Mm si c'est au final, ce n'est pas pris en compte, c est toujours utile.

Pour rappel, deux solutions actuellement pour travailler sur une branche différente sous NextDeploy
- Lancer une nouvelle vm sur cette branche (environ 10min d'install), c'est la solution recommandée qui garantit une plus grande efficience.
- Se connecter sur la vm (en vnc via la webui ou en ssh) et changer de branche "à la manno" via les commandes git.

Il faut voir aussi que le concept de base de NextDeploy est la mise en place d'un cycle de développement en continu. Si on suit ce principe, une nouvelle évolution, ou une nouvelle branche induit une nouvelle vm de test et de validation. Donc en plus de la faisabilité technique compliquée, introduire un système de changement de branches au niveau de la webui irait contre ce principe.

Et puis, en soit, changer de branche n'est pas si éloigné de changer de projet. Donc à ce moment-là, pourquoi pas donner la possibilité de changer de projet :)
